use crate::paths::LaraluxPaths;
use crate::service::{probe_tcp, Service, ServiceError, ServiceKind, SpawnSpec};
use std::path::PathBuf;

pub struct PostgresService {
    port: u16,
}

impl PostgresService {
    pub fn new() -> Self {
        Self { port: 5432 }
    }
    fn datadir(&self, paths: &LaraluxPaths) -> PathBuf {
        paths.data().join("postgres")
    }
    fn initdb_args(&self, paths: &LaraluxPaths) -> Vec<String> {
        vec![
            "-D".to_string(),
            self.datadir(paths).display().to_string(),
            "--username=postgres".to_string(),
            "--auth=trust".to_string(),
            "--encoding=UTF8".to_string(),
        ]
    }
}

impl Default for PostgresService {
    fn default() -> Self {
        Self::new()
    }
}

impl Service for PostgresService {
    fn kind(&self) -> ServiceKind {
        ServiceKind::Postgres
    }
    fn name(&self) -> &str {
        "postgres"
    }
    fn write_config(&self, paths: &LaraluxPaths) -> Result<(), ServiceError> {
        // PostgreSQL keeps its config inside the datadir (generated by initdb);
        // runtime overrides are passed on the command line. Just ensure dirs exist.
        std::fs::create_dir_all(self.datadir(paths))?;
        std::fs::create_dir_all(paths.log())?;
        std::fs::create_dir_all(paths.tmp())?;
        Ok(())
    }
    fn needs_init(&self, paths: &LaraluxPaths) -> bool {
        !self.datadir(paths).join("PG_VERSION").is_file()
    }
    fn init(&self, paths: &LaraluxPaths) -> Result<(), ServiceError> {
        self.write_config(paths)?;
        let tool = crate::bin::resolve_bin("initdb", &crate::layout::managed_bin_dirs(paths))
            .ok_or_else(|| ServiceError::Init("initdb not found".into()))?;
        let status = std::process::Command::new(&tool)
            .args(self.initdb_args(paths))
            .status()
            .map_err(|e| ServiceError::Init(format!("initdb: {e}")))?;
        if !status.success() {
            return Err(ServiceError::Init("initdb failed".into()));
        }
        Ok(())
    }
    fn command(&self, paths: &LaraluxPaths) -> SpawnSpec {
        SpawnSpec::new("postgres")
            .arg("-D")
            .arg(self.datadir(paths).display().to_string())
            .arg("-p")
            .arg(self.port.to_string())
            .arg("-k")
            .arg(paths.tmp().display().to_string())
            .arg("-c")
            .arg("listen_addresses=127.0.0.1")
            .arg("-c")
            .arg("logging_collector=on")
            .arg("-c")
            .arg(format!("log_directory={}", paths.log().display()))
            .arg("-c")
            .arg("log_filename=postgres.log")
    }
    fn health_check(&self, _paths: &LaraluxPaths) -> Result<(), ServiceError> {
        probe_tcp(self.port)
    }
    fn pre_start(&self, paths: &LaraluxPaths) -> Result<(), ServiceError> {
        // Clear a stale postmaster + unix socket from a previous run.
        crate::service::cleanup_stale_endpoint(
            Some(&self.datadir(paths).join("postmaster.pid")),
            Some(&paths.tmp().join(".s.PGSQL.5432")),
        );
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::service::{Service, ServiceKind};

    #[test]
    fn command_and_kind() {
        let p = LaraluxPaths::new("/tmp/lara".into());
        let svc = PostgresService::new();
        let spec = svc.command(&p);
        assert_eq!(spec.program, "postgres");
        assert!(spec.args.iter().any(|a| a == "-D"));
        assert!(spec.args.iter().any(|a| a == "5432"));
        assert!(spec.args.iter().any(|a| a == "listen_addresses=127.0.0.1"));
        assert!(spec.args.iter().any(|a| a == "logging_collector=on"));
        assert!(spec.args.iter().any(|a| a == "log_filename=postgres.log"));
        assert_eq!(svc.kind(), ServiceKind::Postgres);
    }

    #[test]
    fn needs_init_true_until_pg_version_exists() {
        let tmp = std::env::temp_dir().join(format!("lara-pg-{}", std::process::id()));
        let p = LaraluxPaths::new(tmp.clone());
        let svc = PostgresService::new();
        assert!(svc.needs_init(&p));
        std::fs::create_dir_all(p.data().join("postgres")).unwrap();
        std::fs::write(p.data().join("postgres").join("PG_VERSION"), b"16\n").unwrap();
        assert!(!svc.needs_init(&p));
        std::fs::remove_dir_all(&tmp).ok();
    }

    #[test]
    fn initdb_args_use_trust_and_postgres_superuser() {
        let p = LaraluxPaths::new("/tmp/lara".into());
        let svc = PostgresService::new();
        let args = svc.initdb_args(&p);
        assert!(args.contains(&"--username=postgres".to_string()));
        assert!(args.contains(&"--auth=trust".to_string()));
        assert!(args.iter().any(|a| a == "-D"));
    }
}
