//! Laragon Linux core: GUI-independent service orchestration.

pub mod paths;
pub mod bin;
pub mod config;
pub mod service;
pub mod process;
pub mod orchestrator;
pub mod sites;
pub mod site_registry;
pub mod hosts;
pub mod ssl;
pub mod privileged;
pub mod sync;
pub mod setup;
pub mod scaffold;
pub mod php_versions;
pub mod php_static;
pub mod php_cli;
pub mod shell_env;
pub mod terminal;
pub mod coredns;
pub mod mkcert_static;
pub mod nginx_static;
pub mod redis_static;
pub mod mariadb_static;
pub mod certutil_static;
pub mod layout;
pub mod orphans;
pub mod tools;
pub mod progress;

pub use bin::ensure_nginx_bind_cap;
pub use progress::{ProgressEvent, ProgressSink, NullProgress};
pub use layout::{managed_bin_dirs, set_current, installed_versions, apply_versions, probe_version, resolve_installed_version};
pub use config::Config;
pub use tools::{available_versions, install_version, ManagedTool, ToolError, ToolInfo, ToolVersion};
pub use orchestrator::{Orchestrator, ServiceStatus};
pub use paths::LaragonPaths;
pub use process::RealSpawner;
pub use service::registry::build_services;
pub use service::{ServiceKind, ServiceState};
pub use privileged::{PkexecPrivileged, Privileged, SudoPrivileged};
pub use sites::{list_all_sites, scan_sites, ProxySpec, Site, SiteSource};
pub use site_registry::{
    validate_domain, ProxyRoute, ProxySite, RegisteredSite, RegistryError, SiteDomains, SiteRegistry,
};
pub use ssl::MkcertIssuer;
pub use sync::{sync_sites, SyncOutcome};
pub use setup::{detect as detect_components, run_setup, Component, ComponentStatus, CurlDownloader, SetupReport};
pub use scaffold::{CommandRunner, RealCommandRunner, SiteTemplate, ScaffoldError, create_site, CreateReport};
pub use php_versions::{php_versions, PhpVersionInfo};
pub use php_static::{install_php_static, PhpStaticError};
pub use php_cli::{ensure_active_php_cli, install_composer, set_active_php};
pub use shell_env::{disable_shell_path, enable_shell_path};
pub use terminal::{open_terminal, TerminalError};
pub use coredns::{ensure_coredns, corefile, resolved_dropin, CorednsError};
pub use mkcert_static::{install_mkcert, MkcertError};
pub use nginx_static::{install_nginx, NginxError};
pub use redis_static::{install_redis, RedisError};
pub use mariadb_static::{install_mariadb, MariadbError};
pub use certutil_static::{install_certutil, mkcert_install_nss, CertutilError};
pub use orphans::reap as reap_orphans;
