use crate::paths::LaraluxPaths;
use std::path::PathBuf;

/// Build-wide php.ini path the static PHP binary loads via its compiled-in
/// `Configuration File (php.ini) Path`. A symlink here points back into ~/laralux.
pub const SYSTEM_PHP_INI: &str = "/usr/local/etc/php/php.ini";

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PhpIniSettings {
    pub memory_limit: String,
    pub upload_max_filesize: String,
    pub post_max_size: String,
    pub max_execution_time: u32,
    pub timezone: String,
    pub display_errors: bool,
    pub opcache_enable: bool,
}

impl Default for PhpIniSettings {
    fn default() -> Self {
        Self {
            memory_limit: "256M".into(),
            upload_max_filesize: "64M".into(),
            post_max_size: "64M".into(),
            max_execution_time: 120,
            timezone: "UTC".into(),
            display_errors: true,
            opcache_enable: true,
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum PhpIniError {
    #[error("invalid php setting: {0}")]
    Invalid(String),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

/// True for a php size value: optional leading `-`, one or more digits, optional
/// single K/M/G suffix (case-insensitive). Allows `-1` (unlimited). No regex dep.
fn is_size_value(v: &str) -> bool {
    let v = v.trim();
    let b = v.as_bytes();
    if b.is_empty() {
        return false;
    }
    let mut i = 0;
    if b[0] == b'-' {
        i = 1;
    }
    let digits_start = i;
    while i < b.len() && b[i].is_ascii_digit() {
        i += 1;
    }
    if i == digits_start {
        return false; // no digits
    }
    if i == b.len() {
        return true; // pure integer (incl. -1)
    }
    if i == b.len() - 1 {
        return matches!(b[i].to_ascii_uppercase(), b'K' | b'M' | b'G');
    }
    false
}

pub fn validate(s: &PhpIniSettings) -> Result<(), PhpIniError> {
    for (name, val) in [
        ("memory_limit", &s.memory_limit),
        ("upload_max_filesize", &s.upload_max_filesize),
        ("post_max_size", &s.post_max_size),
    ] {
        if !is_size_value(val) {
            return Err(PhpIniError::Invalid(format!(
                "{name}: invalid size '{val}' (use e.g. 256M, 64M, -1)"
            )));
        }
    }
    if s.timezone.trim().is_empty() {
        return Err(PhpIniError::Invalid("date.timezone must not be empty".into()));
    }
    Ok(())
}

pub fn render_php_ini(s: &PhpIniSettings) -> String {
    format!(
        "; Generated by Laralux — edits are overwritten on Apply.\n\
         memory_limit = {mem}\n\
         upload_max_filesize = {up}\n\
         post_max_size = {post}\n\
         max_execution_time = {met}\n\
         date.timezone = {tz}\n\
         display_errors = {de}\n\
         opcache.enable = {oc}\n",
        mem = s.memory_limit,
        up = s.upload_max_filesize,
        post = s.post_max_size,
        met = s.max_execution_time,
        tz = s.timezone,
        de = if s.display_errors { "On" } else { "Off" },
        oc = if s.opcache_enable { "1" } else { "0" },
    )
}

pub fn php_ini_path(paths: &LaraluxPaths) -> PathBuf {
    paths.etc_for("php").join("php.ini")
}

pub fn write_php_ini(paths: &LaraluxPaths, settings: &PhpIniSettings) -> std::io::Result<()> {
    std::fs::create_dir_all(paths.etc_for("php"))?;
    std::fs::write(php_ini_path(paths), render_php_ini(settings))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_match_spec() {
        let d = PhpIniSettings::default();
        assert_eq!(d.memory_limit, "256M");
        assert_eq!(d.upload_max_filesize, "64M");
        assert_eq!(d.post_max_size, "64M");
        assert_eq!(d.max_execution_time, 120);
        assert_eq!(d.timezone, "UTC");
        assert!(d.display_errors);
        assert!(d.opcache_enable);
    }

    #[test]
    fn render_emits_all_directives_with_header() {
        let ini = render_php_ini(&PhpIniSettings::default());
        assert!(ini.starts_with("; Generated by Laralux"));
        assert!(ini.contains("memory_limit = 256M\n"));
        assert!(ini.contains("upload_max_filesize = 64M\n"));
        assert!(ini.contains("post_max_size = 64M\n"));
        assert!(ini.contains("max_execution_time = 120\n"));
        assert!(ini.contains("date.timezone = UTC\n"));
        assert!(ini.contains("display_errors = On\n"));
        assert!(ini.contains("opcache.enable = 1\n"));
    }

    #[test]
    fn render_toggles_off_forms() {
        let mut s = PhpIniSettings::default();
        s.display_errors = false;
        s.opcache_enable = false;
        let ini = render_php_ini(&s);
        assert!(ini.contains("display_errors = Off\n"));
        assert!(ini.contains("opcache.enable = 0\n"));
    }

    #[test]
    fn validate_accepts_sizes_and_minus_one() {
        let mut s = PhpIniSettings::default();
        s.memory_limit = "-1".into();
        s.upload_max_filesize = "64M".into();
        s.post_max_size = "1G".into();
        assert!(validate(&s).is_ok());
    }

    #[test]
    fn validate_rejects_empty_and_bad_size() {
        let mut s = PhpIniSettings::default();
        s.memory_limit = "".into();
        assert!(validate(&s).is_err());
        let mut s2 = PhpIniSettings::default();
        s2.post_max_size = "12x".into();
        assert!(validate(&s2).is_err());
        let mut s3 = PhpIniSettings::default();
        s3.timezone = "   ".into();
        assert!(validate(&s3).is_err());
    }

    #[test]
    fn write_php_ini_creates_file_under_etc_php() {
        let root = std::env::temp_dir().join(format!("lara-phpini-{}", std::process::id()));
        let paths = LaraluxPaths::new(root.clone());
        write_php_ini(&paths, &PhpIniSettings::default()).unwrap();
        let p = php_ini_path(&paths);
        assert_eq!(p, paths.etc_for("php").join("php.ini"));
        let body = std::fs::read_to_string(&p).unwrap();
        assert!(body.contains("memory_limit = 256M"));
        std::fs::remove_dir_all(&root).ok();
    }
}
